name: ci
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v1.**'
jobs:
  build:
    environment: cicd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Determine Docker tags
        id: docker_meta
        run: |
          TAGS="${{ vars.DOCKERHUB_USERNAME }}/gjallarhorn:latest"
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAGS="$TAGS,${{ vars.DOCKERHUB_USERNAME }}/gjallarhorn:${{ github.ref_name }}"
          fi
          echo "tags=$TAGS" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.tags }}